# Site settings
name: Thomas Mortell
email: Thomasm12345@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, BT Young Scientist, Machine Learning, Deep Learning, Startups, Java, Programming, Computer Science, Software Engineering, Internship, Dublin"
skills: "Computer Science Software Engineering student in Maynooth Universtiy, (Kildare)"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: google-plus
    url: https://docs.google.com/document/d/1oKPRrrRVXaI-2rm3KkZ9td-q24-WYo4L3tMGgWZz3UY/edit?usp=sharing
  - title: google-play
    url: https://play.google.com/store/apps/details?id=com.beyzoc.vibrance
  - title: instagram
    url: https://instagram.com/thomas.mortell
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
