# Site settings
name: Thomas Mortell
email: Thomasm12345@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, BT Young Scientist, Machine Learning, Deep Learning, Startups, Java, Programming, Computer Science, Software Engineering, Internship, Dublin, Maynooth University, Maynooth, Universtiy, Student"
skills: "Computer Science Software Engineering student in Maynooth University"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: google
    url: https://play.google.com/store/apps/details?id=com.beyzoc.vibrance
  - title: email
    url: "thomasm12345@gmail.com"
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
